"""Gyrocrypt research helpers for structure probing."""

from .sha256_structure import (
    chirality_histogram64,
    chirality_words_histogram64,
    digest_to_chirality6_mod6_parity,
    digest_to_chirality6_words,
    non_dc_energy_fraction,
    random_messages,
    random_block_words,
    sha256_block_words_from_messages,
    schedule_depth4_projection_lift,
    schedule_omega_trajectory,
    schedule_depth4_frame_signatures,
    sha256_message_schedule,
    sha256_round_chirality_trajectory,
    sha256_round_profiles,
    sha256_digests,
    topk_energy_fractions,
    wht64,
)

__all__ = [
    "chirality_histogram64",
    "chirality_words_histogram64",
    "digest_to_chirality6_mod6_parity",
    "digest_to_chirality6_words",
    "non_dc_energy_fraction",
    "random_messages",
    "random_block_words",
    "sha256_block_words_from_messages",
    "schedule_depth4_projection_lift",
    "schedule_omega_trajectory",
    "schedule_depth4_frame_signatures",
    "sha256_message_schedule",
    "sha256_round_chirality_trajectory",
    "sha256_round_profiles",
    "sha256_digests",
    "topk_energy_fractions",
    "wht64",
]
